### PR TITLE
[H-A-A] Initial commit

### PR DESCRIPTION
**Pull request by HACHIMIam**
Added basic structure of the README.md file

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/nodejs-ar Looks good to you? This repository is probably getting archived but might as well have a good README when it happens....

**Comment by 3imed-jaberi** [comment]
@HACHIMIam , thank you for your first contribution , but you must add the license in a separate file ..

**Comment by ouadie-lahdioui** [comment]
Hi @HACHIMIam, nice to see you here :)

**Comment by HACHIMIam** [comment]
hi @ouadie-lahdioui  this is was my first PR   the PR is almost empty sorry 😐  i wanna bootstrap my profile by participating in open source project  don't hesitate to send me if you have any

**Pull request closed without merging**
